import CreatorsPage from "@/pages/Creators_Page";
import { User } from "@/types/user_type";

const generateUsername = (name: string): string => {
  return name
    .toLowerCase()
    .replace(/\s+/g, "_") // Replace spaces with underscore
    .replace(/[^a-z0-9_]/g, "") // Remove special characters
    .replace(/_+/g, "_"); // Replace multiple underscores with single
};

//GET USERS FROM http://localhost:3000/get-all-users

export const fetchCreators = async (): Promise<User[] | null> => {
  const response = await fetch(
    "https://content-creator-service.vercel.app/get-all-users",
    {
      cache: "no-store",
    }
  );
  const data = await response.json();
  return data.users || null;
};

export const creators = [
  {
    name: "Aitana Lopez",
    username: "aitana_lopez", // Now using generated username
    category: "AI Creator",
    followers: "350K",
    profilePic: "https://picsum.photos/seed/1/200/200",
    coverImage: "https://picsum.photos/seed/11/600/200",
    dataAiHint: "female creator",
    description: "AI Creator | 350k+ followers",
  },
  {
    name: "Darren Till",
    username: "darren_till",
    category: "Athlete",
    followers: "1.2M",
    profilePic: "https://picsum.photos/seed/2/200/200",
    coverImage: "https://picsum.photos/seed/12/600/200",
    dataAiHint: "male boxer",
    description: "Athlete | 1.2M followers",
  },
  {
    name: "Lana Scolaro",
    username: "lana_scolaro",
    category: "DJ",
    followers: "2.1M",
    profilePic: "https://picsum.photos/seed/3/200/200",
    coverImage: "https://picsum.photos/seed/13/600/200",
    dataAiHint: "female dj",
    description: "DJ | 2.1M followers",
  },
  {
    name: "Chesca",
    username: "chesca",
    category: "Musician",
    followers: "480K",
    profilePic: "https://picsum.photos/seed/4/200/200",
    coverImage: "https://picsum.photos/seed/14/600/200",
    description: "AI Creator | 350k+ followers",
    dataAiHint: "female singer",
  },
  {
    name: "Ben Morris",
    username: "ben_morris",
    category: "YouTuber",
    followers: "770K",
    profilePic: "https://picsum.photos/seed/5/200/200",
    coverImage: "https://picsum.photos/seed/15/600/200",
    dataAiHint: "male youtuber",
    description: "YouTuber | 770K followers",
  },
  {
    name: "Sophie Rain",
    username: "sophie_rain",
    category: "Model",
    followers: "5.6M",
    profilePic: "https://picsum.photos/seed/6/200/200",
    coverImage: "https://picsum.photos/seed/16/600/200",
    dataAiHint: "female model",
    description: "Model | 5.6M followers",
  },
  {
    name: "Alex Hormozi",
    username: "alex_hormozi",
    category: "Entrepreneur",
    followers: "2.5M",
    profilePic: "https://picsum.photos/seed/7/200/200",
    coverImage: "https://picsum.photos/seed/17/600/200",
    dataAiHint: "male entrepreneur",
    description: "Entrepreneur | 2.5M followers",
  },
  {
    name: "Lea Martinez",
    description: "AI Creator | 350k+ followers",
    username: "lea_martinez",
    category: "Dancer",
    followers: "1.8M",
    profilePic: "https://picsum.photos/seed/8/200/200",
    coverImage: "https://picsum.photos/seed/18/600/200",
    dataAiHint: "female dancer",
  },
  {
    name: "Noah Beck",
    description: "AI Creator | 350k+ followers",
    username: "noah_beck",
    category: "Influencer",
    followers: "33.8M",
    profilePic: "https://picsum.photos/seed/9/200/200",
    coverImage: "https://picsum.photos/seed/19/600/200",
    dataAiHint: "male influencer",
  },
  {
    name: "James Charles",
    description: "AI Creator | 350k+ followers",
    username: "james_charles",
    category: "Beauty Guru",
    followers: "35.9M",
    profilePic: "https://picsum.photos/seed/10/200/200",
    coverImage: "https://picsum.photos/seed/20/600/200",
    dataAiHint: "male makeup",
  },
  {
    name: "Brent Rivera",
    description: "AI Creator | 350k+ followers",
    username: "brent_rivera",
    category: "Comedian",
    followers: "45.1M",
    profilePic: "https://picsum.photos/seed/21/200/200",
    coverImage: "https://picsum.photos/seed/31/600/200",
    dataAiHint: "male comedian",
  },
  {
    name: "Dixie D'Amelio",
    description: "AI Creator | 350k+ followers",
    username: "dixie_damelio",
    category: "Singer",
    followers: "57.4M",
    profilePic: "https://picsum.photos/seed/22/200/200",
    coverImage: "https://picsum.photos/seed/32/600/200",
    dataAiHint: "female singer",
  },
  {
    name: "Bella Poarch",
    description: "AI Creator | 350k+ followers",
    username: "bella_poarch",
    category: "Creator",
    followers: "92.8M",
    profilePic: "https://picsum.photos/seed/23/200/200",
    coverImage: "https://picsum.photos/seed/33/600/200",
    dataAiHint: "female creator",
  },
  {
    name: "Sommer Ray",
    description: "AI Creator | 350k+ followers",
    username: "sommer_ray",
    category: "Fitness Model",
    followers: "26.4M",
    profilePic: "https://picsum.photos/seed/24/200/200",
    coverImage: "https://picsum.photos/seed/34/600/200",
    dataAiHint: "female fitness",
  },
  {
    name: "David Dobrik",
    description: "AI Creator | 350k+ followers",
    username: "david_dobrik",
    category: "Vlogger",
    followers: "25.9M",
    profilePic: "https://picsum.photos/seed/25/200/200",
    coverImage: "https://picsum.photos/seed/35/600/200",
    dataAiHint: "male vlogger",
  },
  {
    name: "Emma Chamberlain",
    description: "AI Creator | 350k+ followers",
    username: "emma_chamberlain",
    category: "Lifestyle",
    followers: "16.2M",
    profilePic: "https://picsum.photos/seed/26/200/200",
    coverImage: "https://picsum.photos/seed/36/600/200",
    dataAiHint: "female lifestyle",
  },
  {
    name: "PewDiePie",
    description: "AI Creator | 350k+ followers",
    username: "pewdiepie",
    category: "Gamer",
    followers: "111M",
    profilePic: "https://picsum.photos/seed/27/200/200",
    coverImage: "https://picsum.photos/seed/37/600/200",
    dataAiHint: "male gamer",
  },
  {
    name: "Jeffree Star",
    description: "AI Creator | 350k+ followers",
    username: "jeffree_star",
    category: "Entrepreneur",
    followers: "15.9M",
    profilePic: "https://picsum.photos/seed/28/200/200",
    coverImage: "https://picsum.photos/seed/38/600/200",
    dataAiHint: "makeup entrepreneur",
  },
  {
    name: "Ninja",
    description: "AI Creator | 350k+ followers",
    username: "ninja",
    category: "Pro Gamer",
    followers: "19M",
    profilePic: "https://picsum.photos/seed/29/200/200",
    coverImage: "https://picsum.photos/seed/39/600/200",
    dataAiHint: "male pro gamer",
  },
  {
    name: "Pokimane",
    description: "AI Creator | 350k+ followers",
    username: "pokimane",
    category: "Streamer",
    followers: "9.4M",
    profilePic: "https://picsum.photos/seed/30/200/200",
    coverImage: "https://picsum.photos/seed/40/600/200",
    dataAiHint: "female streamer",
  },
  {
    name: "Amouranth",
    description: "AI Creator | 350k+ followers",
    username: "amouranth",
    category: "Cosplayer",
    followers: "6.4M",
    profilePic: "https://picsum.photos/seed/41/200/200",
    coverImage: "https://picsum.photos/seed/51/600/200",
    dataAiHint: "female cosplayer",
  },
  {
    name: "Logan Paul",
    description: "AI Creator | 350k+ followers",
    username: "logan_paul",
    category: "Boxer",
    followers: "23.6M",
    profilePic: "https://picsum.photos/seed/42/200/200",
    coverImage: "https://picsum.photos/seed/52/600/200",
    dataAiHint: "male boxer",
  },
  {
    name: "MrBeast",
    description: "AI Creator | 350k+ followers",
    username: "mrbeast",
    category: "Philanthropist",
    followers: "250M",
    profilePic: "https://picsum.photos/seed/43/200/200",
    coverImage: "https://picsum.photos/seed/53/600/200",
    dataAiHint: "male philanthropist",
  },
  {
    name: "Tana Mongeau",
    description: "AI Creator | 350k+ followers",
    username: "tana_mongeau",
    category: "Storyteller",
    followers: "5.4M",
    profilePic: "https://picsum.photos/seed/44/200/200",
    coverImage: "https://picsum.photos/seed/54/600/200",
    dataAiHint: "female storyteller",
  },
  {
    name: "Corinna Kopf",
    description: "AI Creator | 350k+ followers",
    username: "corinna_kopf",
    category: "Gamer",
    followers: "6.7M",
    profilePic: "https://picsum.photos/seed/45/200/200",
    coverImage: "https://picsum.photos/seed/55/600/200",
    dataAiHint: "female gamer",
  },
  {
    name: "Alissa Violet",
    description: "AI Creator | 350k+ followers",
    username: "alissa_violet",
    category: "Model",
    followers: "11.8M",
    profilePic: "https://picsum.photos/seed/46/200/200",
    coverImage: "https://picsum.photos/seed/56/600/200",
    dataAiHint: "female model",
  },
  {
    name: "Valkyrae",
    description: "AI Creator | 350k+ followers",
    username: "valkyrae",
    category: "Gamer",
    followers: "4.1M",
    profilePic: "https://picsum.photos/seed/47/200/200",
    coverImage: "https://picsum.photos/seed/57/600/200",
    dataAiHint: "female gamer",
  },
  {
    name: "Dr Disrespect",
    description: "AI Creator | 350k+ followers",
    username: "dr_disrespect",
    category: "Streamer",
    followers: "4.5M",
    profilePic: "https://picsum.photos/seed/48/200/200",
    coverImage: "https://picsum.photos/seed/58/600/200",
    dataAiHint: "male streamer",
  },
  {
    name: "xQc",
    description: "AI Creator | 350k+ followers",
    username: "xqc",
    category: "Streamer",
    followers: "11.9M",
    profilePic: "https://picsum.photos/seed/49/200/200",
    coverImage: "https://picsum.photos/seed/59/600/200",
    dataAiHint: "male streamer",
  },
  {
    name: "Adebisi",
    description: "AI Creator | 350k+ followers",
    username: "adebisi",
    category: "Athlete",
    followers: "1.1M",
    profilePic: "https://picsum.photos/seed/50/200/200",
    coverImage: "https://picsum.photos/seed/60/200",
    dataAiHint: "male athlete",
  },
  {
    name: "Nadia",
    description: "AI Creator | 350k+ followers",
    username: "nadia",
    category: "Gamer",
    followers: "1.3M",
    profilePic: "https://picsum.photos/seed/61/200/200",
    coverImage: "https://picsum.photos/seed/71/600/200",
    dataAiHint: "female gamer",
  },
  {
    name: "Kylie Jenner",
    description: "AI Creator | 350k+ followers",
    username: "kylie_jenner",
    category: "Entrepreneur",
    followers: "398M",
    profilePic: "https://picsum.photos/seed/62/200/200",
    coverImage: "https://picsum.photos/seed/72/600/200",
    dataAiHint: "female entrepreneur",
  },
  {
    name: "Kim Kardashian",
    description: "AI Creator | 350k+ followers",
    username: "kim_kardashian",
    category: "Celebrity",
    followers: "363M",
    profilePic: "https://picsum.photos/seed/63/200/200",
    coverImage: "https://picsum.photos/seed/73/600/200",
    dataAiHint: "female celebrity",
  },
  {
    name: "Selena Gomez",
    description: "AI Creator | 350k+ followers",
    username: "selena_gomez",
    category: "Musician",
    followers: "427M",
    profilePic: "https://picsum.photos/seed/64/200/200",
    coverImage: "https://picsum.photos/seed/74/600/200",
    dataAiHint: "female musician",
  },
  {
    name: "The Rock",
    description: "AI Creator | 350k+ followers",
    username: "the_rock",
    category: "Actor",
    followers: "388M",
    profilePic: "https://picsum.photos/seed/65/200/200",
    coverImage: "https://picsum.photos/seed/75/600/200",
    dataAiHint: "male actor",
  },
  {
    name: "Ariana Grande",
    description: "AI Creator | 350k+ followers",
    username: "ariana_grande",
    category: "Musician",
    followers: "378M",
    profilePic: "https://picsum.photos/seed/66/200/200",
    coverImage: "https://picsum.photos/seed/76/600/200",
    dataAiHint: "female musician",
  },
  {
    name: "Cristiano Ronaldo",
    description: "AI Creator | 350k+ followers",
    username: "cristiano_ronaldo",
    category: "Athlete",
    followers: "600M",
    profilePic: "https://picsum.photos/seed/67/200/200",
    coverImage: "https://picsum.photos/seed/77/600/200",
    dataAiHint: "male athlete",
  },
  {
    name: "Lionel Messi",
    description: "AI Creator | 350k+ followers",
    username: "lionel_messi",
    category: "Athlete",
    followers: "482M",
    profilePic: "https://picsum.photos/seed/68/200/200",
    coverImage: "https://picsum.photos/seed/78/600/200",
    dataAiHint: "male athlete",
  },
  {
    name: "Beyonce",
    description: "AI Creator | 350k+ followers",
    username: "beyonce",
    category: "Musician",
    followers: "315M",
    profilePic: "https://picsum.photos/seed/69/200/200",
    coverImage: "https://picsum.photos/seed/79/600/200",
    dataAiHint: "female musician",
  },
  {
    name: "Justin Bieber",
    description: "AI Creator | 350k+ followers",
    username: "justin_bieber",
    category: "Musician",
    followers: "292M",
    profilePic: "https://picsum.photos/seed/70/200/200",
    coverImage: "https://picsum.photos/seed/80/600/200",
    dataAiHint: "male musician",
  },
];

export default async function Page() {
  const creators = await fetchCreators();
  return <CreatorsPage creators={creators ?? []} />;
}
